[WIP] APPS-1267 Feature/add insurance to shipment and orders
shipit-team/prestashop pull request #7
Opened 2021-05-23 23:34 UTC by multinauta

Refers: https://shipitchile.atlassian.net/browse/APPS-1267

Why I'm adding these lines of code:

-To add insurance to order and shipment
-To add Composer to project

Test:

Shipment

![Screenshot from 2021-05-23 16-08-06](https://user-images.githubusercontent.com/8929172/119280083-b142d800-bbfd-11eb-9270-8753adcbca0c.png)

Order

![Screenshot from 2021-05-23 16-16-03](https://user-images.githubusercontent.com/8929172/119280097-c0298a80-bbfd-11eb-98f2-a836de86a16f.png)

2021-06-08 15:33 UTC, David25848 approved these changes, later dismissed

2021-06-09 21:14 UTC, mgraterol submitted a review, later dismissed

2021-06-09 21:35 UTC, Barbycris submitted a review, later dismissed

2021-06-16 19:57 UTC, Barbycris approved these changes, later dismissed

2021-06-16 19:58 UTC, mgraterol submitted a review, later dismissed

2021-06-16 19:58 UTC, David25848 submitted a review, later dismissed

2021-06-16 21:05 UTC, FelipeChibey requested changes

2021-06-16 21:05 UTC, FelipeChibey commented on rg_shipit/rg_shipit.php
> +        if ($insuranceProducts!='') $insuranceProducts .= ',';
```suggestion
        if ($insuranceProducts != '') $insuranceProducts .= ',';
```

can be null insuranceProducts?

2021-06-16 21:05 UTC, FelipeChibey commented on rg_shipit/rg_shipit.php
> +      if ($insuranceProducts!='') $insuranceProducts .= ',';
```suggestion
      if ($insuranceProducts != '') $insuranceProducts .= ',';
```

2021-06-16 21:05 UTC, FelipeChibey commented on rg_shipit/shipit_service/ShipitInsurance.php
> +      return $insurance_active;
```suggestion
      return ($insurance_setting->insurance->active) && ($total > $insurance_setting->insurance->amount);
```

2021-06-16 21:28 UTC, Barbycris submitted a review, later dismissed

2021-06-16 21:28 UTC, mgraterol approved these changes, later dismissed

2021-06-16 21:36 UTC, FelipeChibey approved these changes, later dismissed

2021-06-17 21:53 UTC, David25848 approved these changes, later dismissed

2021-06-24 14:56 UTC, Barbycris approved these changes

2021-06-24 14:56 UTC, mgraterol approved these changes

2021-06-24 15:00 UTC, davidmaring7 approved these changes

2021-06-30 19:44 UTC, HaNdlezz approved these changes

2021-07-01 21:47 UTC, merged